"""Whose data is in `data/`, under what terms, and whether it may leave this machine.

Every record names its source (`_meta.source`; a buried probe, its `parent_source`), every raw file sits under a
pinned catalog item, so each file in `data/` resolves to the sources it contains. Each source's licence was checked
at its primary source (the pinned dataset card, the licence file shipped in the archive, or the publisher's terms);
`evidence` says where. A file takes the most restrictive class among its sources:

- `open`: permissive (MIT, Apache-2.0, BSD, CC0, CC-BY, public domain, "free use");
- `share-alike`: CC-BY-SA; derived data must keep the licence;
- `non-commercial`: CC-BY-NC or research-only terms; redistribution allowed for non-commercial use, marked as such;
- `unspecified`: no licence stated; kept to a private copy, never published;
- `restricted`: the terms forbid redistribution; never uploaded anywhere.

`den licences` writes the notices into `data/` (`LICENSES.md`, `LICENSES/`, `README.md` as the Hub dataset card, and a
`SOURCE-LICENSE.md` beside every dataset, saying what each file there holds and under what terms); `scripts/mirror.py` uploads only what `allowed` permits. Not legal advice:
the classes are conservative readings of each source's own terms.
"""

from __future__ import annotations

import argparse
import json
import shutil
import tarfile
import zipfile
from collections import defaultdict
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from fnmatch import fnmatch
from pathlib import Path
from typing import Literal

from .catalog import NOTICE_FILE
from .pins import ITEMS

type Kind = Literal["open", "share-alike", "non-commercial", "unspecified", "restricted"]
RANK: dict[Kind, int] = {"open": 0, "share-alike": 1, "non-commercial": 2, "unspecified": 3, "restricted": 4}
TEXTS = Path("licences")  # canonical licence texts, from spdx/license-list-data at SPDX_COMMIT
SPDX_COMMIT = "31ba1a50e5397e00a304dbadc76531740e89ee48"  # v3.29.0
IGNORE = (".normalize/*", ".breadth/*", ".cache/*", "*/.cache/*", "*.part", "*.tmp", ".DS_Store", "*/.DS_Store",
          "MANIFEST.json")  # fmt: skip


def _generated(rel: str) -> bool:
    """A notice `write` produces, not data."""
    return rel in ("README.md", "LICENSES.md") or rel.startswith("LICENSES/") or rel.endswith(f"/{NOTICE_FILE}")


@dataclass(frozen=True, slots=True)
class Source:
    key: str
    title: str
    licence: str  # as the source states it
    kind: Kind
    url: str  # where the terms are stated
    evidence: str  # what was read, and what it says
    attribution: str
    names: tuple[str, ...] = ()  # `_meta.source` values and catalog item names that are this source
    texts: tuple[str, ...] = ()  # SPDX ids whose canonical text applies


KEV = "Jared Palmer, Kev 1.0 (github.com/jaredpalmer/kev, huggingface.co/datasets/jaredpalmer/kev-suites)"
SOURCES: tuple[Source, ...] = (
    # ---- generated by Kev (his code, Apache-2.0): policies, compositions, skills, diagnostics, unknowables
    Source("kev", "Kev 1.0 generated data", "Apache-2.0", "open", "https://github.com/jaredpalmer/kev/blob/fe64b1274ea7f80d4095866df90666abb03e9cf6/LICENSE",
           "Kev's repository LICENSE at the pinned commit is Apache-2.0; these records are produced by its generators with code labels (skills manifest: 'programmatic: ... no model or human judgement').",
           KEV, ("compositional", "legacy_policy", "contrastive", "legacy_holdout", "composition_holdout", "unknowable", "unknowable_control",
                 "binding_diagnostic", "night2_dates", "night2_unknowable", "night2_unknowable_control", "hard_*", "kev-suites"), ("Apache-2.0",)),
    # ---- Kev's core: ten public datasets
    Source("ag-news", "AG News", "non-commercial academic use", "non-commercial", "http://www.di.unipi.it/~gulli/AG_corpus_of_news_articles.html",
           "Card at the pinned revision: licence 'unknown'; the corpus 'is provided by the academic community for research purposes ... and any other non-commercial activity'.",
           "Zhang, Zhao, LeCun, Character-level Convolutional Networks for Text Classification (NeurIPS 2015); A. Gulli's AG corpus",
           ("agnews", "topic/ag-news")),
    Source("amazon", "Multilingual Amazon Reviews Corpus (English)", "Amazon Reviews Corpus licence (academic research only, no republication)", "restricted",
           "https://huggingface.co/datasets/defunct-datasets/amazon_reviews_multi",
           "SetFit's re-upload is tagged apache-2.0, but the text is Amazon's corpus, whose licence grants academic research use and says you 'may not resell, republish, or make any commercial use' of it; Amazon withdrew the corpus (defunct on the Hub and the AWS registry).",
           "Keung et al., The Multilingual Amazon Reviews Corpus (EMNLP 2020)", ("amazon", "sentiment/amazon-reviews")),
    Source("banking77", "BANKING77", "CC-BY-4.0", "open", "https://huggingface.co/datasets/legacy-datasets/banking77",
           "Card at the pinned revision: cc-by-4.0.", "Casanueva et al., Efficient Intent Detection with Dual Sentence Encoders (2020)",
           ("banking77", "intent/banking77"), ("CC-BY-4.0",)),
    Source("boolq", "BoolQ", "CC-BY-SA-3.0", "share-alike", "https://huggingface.co/datasets/google/boolq",
           "Card at the pinned revision: cc-by-sa-3.0 (passages from Wikipedia).", "Clark et al., BoolQ: Exploring the Surprising Difficulty of Natural Yes/No Questions (NAACL 2019)",
           ("boolq", "reading/boolq"), ("CC-BY-SA-3.0",)),
    Source("dbpedia14", "DBpedia-14", "CC-BY-SA-3.0", "share-alike", "https://huggingface.co/datasets/fancyzhx/dbpedia_14",
           "Card at the pinned revision: cc-by-sa-3.0.", "Zhang, Zhao, LeCun (NeurIPS 2015); DBpedia (Lehmann et al., 2015)",
           ("dbpedia14", "topic/dbpedia14"), ("CC-BY-SA-3.0",)),
    Source("imdb", "Large Movie Review Dataset (IMDB)", "none stated", "unspecified", "https://ai.stanford.edu/~amaas/data/sentiment/",
           "Card at the pinned revision: 'other', licensing 'More Information Needed'; the dataset page states no licence. Reviews are IMDb user content.",
           "Maas et al., Learning Word Vectors for Sentiment Analysis (ACL 2011)", ("imdb", "sentiment/imdb")),
    Source("mnli", "MultiNLI", "OANC licence; fiction under CC-BY-SA-3.0 / CC-BY-3.0", "share-alike", "https://huggingface.co/datasets/nyu-mll/multi_nli",
           "Card at the pinned revision: 'The majority of the corpus is released under the OANC's license ... Seven Swords is available under a Creative Commons Share-Alike 3.0 Unported License'.",
           "Williams, Nangia, Bowman, A Broad-Coverage Challenge Corpus for Sentence Understanding through Inference (NAACL 2018)",
           ("mnli", "reading/multinli"), ("CC-BY-SA-3.0", "CC-BY-3.0")),
    Source("sst5", "Stanford Sentiment Treebank (SST-5)", "none stated", "unspecified", "https://nlp.stanford.edu/sentiment/",
           "SetFit/sst5 card has no licence; the Stanford page states none. Sentences are Rotten Tomatoes review snippets.",
           "Socher et al., Recursive Deep Models for Semantic Compositionality Over a Sentiment Treebank (EMNLP 2013)", ("sst5", "sentiment/sst5")),
    Source("trec", "TREC question classification", "none stated", "unspecified", "https://cogcomp.seas.upenn.edu/Data/QA/QC/",
           "CogComp/trec card has no licence; the CogComp page states none.", "Li and Roth, Learning Question Classifiers (COLING 2002)", ("trec", "topic/trec")),
    Source("yelp", "Yelp Review Full", "Yelp Dataset Terms of Use", "restricted",
           "https://s3-media3.fl.yelpcdn.com/assets/srv0/engineering_pages/bea5c1e92bf3/assets/vendor/yelp-dataset-agreement.pdf",
           "Card at the pinned revision points to the Yelp dataset agreement, which licenses non-commercial use and says you will not 'display, perform, or distribute any of the Data' (4A) nor 'rent, lease, sell, transfer, assign, or sublicense' it (4H).",
           "Zhang, Zhao, LeCun (NeurIPS 2015); Yelp Dataset Challenge", ("yelp", "sentiment/yelp-full")),
    # ---- held-out and probe sources
    Source("emotion", "dair-ai/emotion", "research and educational use only", "non-commercial", "https://huggingface.co/datasets/dair-ai/emotion",
           "Card at the pinned revision: 'The dataset should be used for educational and research purposes only.'",
           "Saravia et al., CARER: Contextualized Affect Representations for Emotion Recognition (EMNLP 2018)", ("emotion", "transfer/emotion")),
    Source("mmlu", "MMLU", "MIT", "open", "https://huggingface.co/datasets/cais/mmlu", "Card at the pinned revision: mit.",
           "Hendrycks et al., Measuring Massive Multitask Language Understanding (ICLR 2021)", ("mmlu", "transfer/mmlu"), ("MIT",)),
    Source("mmlu-pro", "MMLU-Pro", "MIT", "open", "https://huggingface.co/datasets/TIGER-Lab/MMLU-Pro", "Card at the pinned revision: mit.",
           "Wang et al., MMLU-Pro (NeurIPS 2024)", ("mmlu_pro", "transfer/mmlu-pro"), ("MIT",)),
    Source("paws", "PAWS (Wiki)", "free use, acknowledgement appreciated", "open", "https://huggingface.co/datasets/google-research-datasets/paws",
           "Card at the pinned revision: 'The dataset may be freely used for any purpose, although acknowledgement of Google LLC (\"Google\") as the data source would be appreciated.'",
           "Zhang, Baldridge, He, PAWS: Paraphrase Adversaries from Word Scrambling (NAACL 2019)", ("paws", "transfer/paws")),
    Source("qnli", "QNLI (GLUE, from SQuAD)", "CC-BY-SA-4.0 (SQuAD)", "share-alike", "https://rajpurkar.github.io/SQuAD-explorer/",
           "GLUE card: 'We refer users to the original licenses accompanying each dataset'; QNLI is built from SQuAD, which its site licenses CC BY-SA 4.0.",
           "Wang et al., GLUE (ICLR 2019); Rajpurkar et al., SQuAD (EMNLP 2016)", ("qnli", "transfer/qnli"), ("CC-BY-SA-4.0",)),
    Source("sciq", "SciQ", "CC-BY-NC-3.0", "non-commercial", "https://huggingface.co/datasets/allenai/sciq", "Card at the pinned revision: cc-by-nc-3.0.",
           "Welbl, Liu, Gardner, Crowdsourcing Multiple Choice Science Questions (W-NUT 2017)", ("sciq", "transfer/sciq"), ("CC-BY-NC-3.0",)),
    Source("tweeteval-offensive", "TweetEval offensive (OLID)", "none stated; Twitter/X Terms of Service apply", "unspecified",
           "https://huggingface.co/datasets/cardiffnlp/tweet_eval",
           "Card at the pinned revision: licence 'unknown'; 'All of the datasets require complying with Twitter Terms Of Service and Twitter API Terms Of Service'.",
           "Barbieri et al., TweetEval (Findings of EMNLP 2020); Zampieri et al., OLID (NAACL 2019)", ("tweet_offensive", "transfer/tweeteval-offensive")),
    # ---- documents and devtools suites
    Source("cfpb", "CFPB Consumer Complaint Database", "US government work (public domain)", "open", "https://www.consumerfinance.gov/data-research/consumer-complaints/",
           "Kev's documents manifest: 'US CFPB consumer complaint database, US government work (public domain)'; the Hub copy (davidheineman/consumer-finance-complaints-large) is tagged apache-2.0. Labels are CFPB's own, checked by model judges.",
           "Consumer Financial Protection Bureau", ("cfpb", "documents/cfpb-complaints")),
    Source("codereviewer", "CodeReviewer (diff quality)", "CC-BY-4.0; code under each project's permissive licence", "open", "https://zenodo.org/records/6900648",
           "Kev's devtools manifest: CC-BY-4.0 on Zenodo; only projects whose GitHub licence is permissive were kept (GPL/AGPL/LGPL/MPL and unlicensed dropped).",
           "Li et al., Automating Code Review Activities by Large-Scale Pre-training (ESEC/FSE 2022)", ("codereviewer", "devtools/codereviewer"), ("CC-BY-4.0",)),
    Source("commitpackft", "CommitPackFT", "MIT (dataset); rows kept only under permissive repository licences", "open", "https://huggingface.co/datasets/bigcode/commitpackft",
           "Card: mit; Kev's devtools manifest keeps rows only when the repository licence is mit, apache-2.0, bsd-2/3-clause, isc, cc0-1.0 or unlicense.",
           "Muennighoff et al., OctoPack (ICLR 2024)", ("commitpackft", "devtools/commitpackft"), ("MIT",)),
    Source("flakeflagger", "FlakeFlagger", "CC-BY-4.0 (data); BSD-3-Clause (repository); test code under each project's licence", "open", "https://zenodo.org/records/4450723",
           "Kev's devtools manifest: each project's licence at the pinned commit was read; LGPL/EPL projects dropped.",
           "Alshammari et al., FlakeFlagger (ICSE 2021)", ("flakeflagger", "devtools/flakeflagger-results", "devtools/flakeflagger-projects", "devtools/flakeflagger-code"),
           ("CC-BY-4.0", "BSD-3-Clause")),
    Source("aegis", "Aegis AI Content Safety 2.0", "CC-BY-4.0", "open", "https://huggingface.co/datasets/nvidia/Aegis-AI-Content-Safety-Dataset-2.0",
           "Card at the pinned revision: cc-by-4.0 (its out-of-scope note asks that the data be used for research on safety). AART-matching prompts were dropped.",
           "Ghosh et al., Aegis 2.0 (NAACL 2025)", ("aegis", "safety/aegis"), ("CC-BY-4.0",)),
    Source("aart", "AART", "CC-BY-4.0", "open", "https://huggingface.co/datasets/walledai/AART", "Card at the pinned revision: cc-by-4.0. Used only to filter Aegis.",
           "Radharapu et al., AART (EMNLP 2023 industry)", ("safety/aart-filter",), ("CC-BY-4.0",)),
    Source("when2call", "When2Call", "CC-BY-4.0", "open", "https://huggingface.co/datasets/nvidia/When2Call", "Card at the pinned revision: cc-by-4.0.",
           "Ross et al., When2Call (NAACL 2025)", ("when2call", "devtools/when2call"), ("CC-BY-4.0",)),
    Source("prompt-injection", "Prompt injections (deepset, Lakera Gandalf)", "Apache-2.0 (deepset); MIT (Lakera)", "open",
           "https://huggingface.co/datasets/deepset/prompt-injections", "Cards at the pinned revisions: apache-2.0 (deepset/prompt-injections), mit (Lakera/gandalf_ignore_instructions).",
           "deepset; Lakera", ("prompt_injection", "devtools/prompt-injection", "devtools/prompt-injection-deepset", "devtools/prompt-injection-gandalf"),
           ("Apache-2.0", "MIT")),
    Source("semif", "SemIf", "MIT", "open", "https://github.com/TheoLeeCJ/SemIf", "Kev's semif-v1 manifest: external repo TheoLeeCJ/SemIf@ca3ba65, license MIT.",
           "TheoLeeCJ, SemIf", ("semif_authored", "semif_perturbation"), ("MIT",)),
    # ---- round-2 trainable sources
    Source("arc", "AI2 ARC", "CC-BY-SA-4.0", "share-alike", "https://huggingface.co/datasets/allenai/ai2_arc", "Card at the pinned revision: cc-by-sa-4.0.",
           "Clark et al., Think you have Solved Question Answering? Try ARC (2018)", ("knowledge/arc",), ("CC-BY-SA-4.0",)),
    Source("openbookqa", "OpenBookQA", "Apache-2.0", "open", "https://github.com/allenai/OpenBookQA",
           "Hub card licence 'unknown'; the release repository allenai/OpenBookQA is Apache-2.0 (GitHub licence API).",
           "Mihaylov et al., Can a Suit of Armor Conduct Electricity? (EMNLP 2018)", ("knowledge/openbookqa",), ("Apache-2.0",)),
    Source("commonsenseqa", "CommonsenseQA", "MIT", "open", "https://huggingface.co/datasets/tau/commonsense_qa", "Card at the pinned revision: mit.",
           "Talmor et al., CommonsenseQA (NAACL 2019)", ("knowledge/commonsenseqa",), ("MIT",)),
    Source("qasc", "QASC", "CC-BY-4.0", "open", "https://huggingface.co/datasets/allenai/qasc", "Card at the pinned revision: cc-by-4.0.",
           "Khot et al., QASC (AAAI 2020)", ("knowledge/qasc",), ("CC-BY-4.0",)),
    Source("massive", "MASSIVE (en-US)", "CC-BY-4.0", "open", "https://github.com/alexa/massive/blob/main/NOTICE.md",
           "Hub card at the pinned revision has no licence field; the release NOTICE: 'The MASSIVE dataset is licensed under CC BY 4.0' (from SLURP, CC BY 4.0).",
           "FitzGerald et al., MASSIVE (ACL 2023)", ("intent/massive-en",), ("CC-BY-4.0",)),
    Source("glaive", "Glaive function calling v2", "Apache-2.0", "open", "https://huggingface.co/datasets/glaiveai/glaive-function-calling-v2",
           "Card at the pinned revision: apache-2.0.", "Glaive AI", ("tools/glaive-function-calling",), ("Apache-2.0",)),
    # ---- breadth-v1 (Kev's mappings; records reproduced byte for byte)
    Source("musr", "MuSR", "CC-BY-4.0", "open", "https://huggingface.co/datasets/TAUR-Lab/MuSR", "Card at the pinned revision: cc-by-4.0.",
           "Sprague et al., MuSR (ICLR 2024)", ("musr", "breadth/knowledge/musr"), ("CC-BY-4.0",)),
    Source("sata-bench", "SATA-Bench", "CC-BY-NC-4.0", "non-commercial", "https://huggingface.co/datasets/sata-bench/sata-bench",
           "Card at the pinned revision: cc-by-nc-4.0 (the GitHub code is MIT).", "Xu et al., SATA-Bench (2025)", ("sata_bench", "breadth/knowledge/sata-bench"), ("CC-BY-NC-4.0",)),
    Source("chessbench", "ChessBench action values", "CC-BY-4.0, with lichess positions under CC0", "open", "https://github.com/google-deepmind/searchless_chess",
           "Repository README: 'Some portions of the dataset are in the public domain by a Creative Commons CC0 license from lichess.org. The remainder of the dataset is licensed under Creative Commons Attribution 4.0'.",
           "Ruoss et al., Amortized Planning with Large-Scale Transformers (NeurIPS 2024)", ("chessbench", "breadth/knowledge/chessbench"), ("CC-BY-4.0", "CC0-1.0")),
    Source("contractnli", "ContractNLI", "CC-BY-4.0", "open", "https://stanfordnlp.github.io/contract-nli/",
           "The archive's TERMS (Hitachi America): use 'in accordance with the terms and conditions of the Creative Commons Attribution 4.0 International Public License'; LICENSE is CC BY 4.0.",
           "Koreeda and Manning, ContractNLI (Findings of EMNLP 2021)", ("contractnli", "breadth/language/contractnli"), ("CC-BY-4.0",)),
    Source("hellaswag", "HellaSwag (ActivityNet items)", "MIT", "open", "https://huggingface.co/datasets/Rowan/hellaswag",
           "Card at the pinned revision: 'MIT'. breadth-v1 keeps only ActivityNet-derived items; the wikiHow half is left out after wikiHow's DMCA notice took down the HellaSwag GitHub repository.",
           "Zellers et al., HellaSwag (ACL 2019)", ("hellaswag",), ("MIT",)),
    Source("hellaswag-raw", "HellaSwag validation file (raw, with wikiHow items)", "MIT, subject to wikiHow's DMCA notice", "restricted",
           "https://github.com/github/dmca/blob/master/2026/09/2026-09-14-wikihow.md",
           "The raw validation parquet still holds the wikiHow-derived contexts named in wikiHow's 2026-09-14 DMCA notice (Kev's breadth-v1 mapping notes the takedown); not redistributed.",
           "Zellers et al., HellaSwag (ACL 2019)", ("breadth/language/hellaswag",), ("MIT",)),
    Source("clinc150", "CLINC150 (OOS)", "CC-BY-3.0", "open", "https://huggingface.co/datasets/clinc/clinc_oos",
           "Card at the pinned revision: cc-by-3.0; clinc/oos-eval LICENSE is CC BY 3.0 Unported.",
           "Larson et al., An Evaluation Dataset for Intent Classification and Out-of-Scope Prediction (EMNLP 2019)",
           ("clinc150", "breadth/retrieval/clinc150", "breadth/retrieval/clinc150-domains"), ("CC-BY-3.0",)),
    Source("sgd", "Schema-Guided Dialogue (+ SGD-X)", "CC-BY-SA-4.0", "share-alike", "https://github.com/google-research-datasets/dstc8-schema-guided-dialogue",
           "The archive's LICENSE.txt: Attribution-ShareAlike 4.0 International.", "Rastogi et al., SGD (AAAI 2020); Lee et al., SGD-X (AAAI 2022)",
           ("sgd", "breadth/retrieval/sgd"), ("CC-BY-SA-4.0",)),
    Source("bright", "BRIGHT", "CC-BY-4.0", "open", "https://huggingface.co/datasets/xlangai/BRIGHT", "Card at the pinned revision: cc-by-4.0.",
           "Su et al., BRIGHT (ICLR 2025)", ("bright", "breadth/retrieval/bright"), ("CC-BY-4.0",)),
    Source("bfcl", "Berkeley Function-Calling Leaderboard", "Apache-2.0", "open", "https://huggingface.co/datasets/gorilla-llm/Berkeley-Function-Calling-Leaderboard",
           "Card at the pinned revision: apache-2.0.", "Patil et al., BFCL (ICML 2025)", ("bfcl", "breadth/tools/bfcl"), ("Apache-2.0",)),
    Source("toolret", "ToolRet", "Apache-2.0 (release); queries and tools re-published from their source benchmarks", "open", "https://github.com/mangopy/tool-retrieval-benchmark",
           "Hub cards have no licence field; the release repository is Apache-2.0 (GitHub licence API). Kev's breadth-v1 leaves out the apigen subset, whose card is research-only.",
           "Shi et al., Retrieval Models Aren't Tool-Savvy (Findings of ACL 2025)", ("toolret", "breadth/tools/toolret-queries", "breadth/tools/toolret-tools"), ("Apache-2.0",)),
    Source("apibank", "API-Bank", "MIT", "open", "https://huggingface.co/datasets/liminghao1630/API-Bank", "Card at the pinned revision: mit.",
           "Li et al., API-Bank (EMNLP 2023)", ("apibank", "breadth/tools/apibank"), ("MIT",)),
    Source("routerbench", "RouterBench (MMLU, Winogrande, MBPP items)", "MIT", "open", "https://github.com/withmartian/routerbench",
           "The release repository is MIT (GitHub licence API); breadth-v1 uses only its MMLU, Winogrande and MBPP prompts and the 0/1 correctness of each model.",
           "Hu et al., RouterBench (2024)", ("routerbench",), ("MIT",)),
    Source("routerbench-raw", "RouterBench 0-shot file (raw)", "MIT, embedding third-party prompts incl. HellaSwag wikiHow items", "restricted",
           "https://github.com/github/dmca/blob/master/2026/09/2026-09-14-wikihow.md",
           "The raw pickle bundles every RouterBench prompt, including HellaSwag's wikiHow contexts under wikiHow's DMCA notice; not redistributed.",
           "Hu et al., RouterBench (2024)", ("breadth/tools/routerbench",), ("MIT",)),
    Source("humicroedit", "Humicroedit (SemEval-2020 Task 7)", "none stated (cite the task paper)", "unspecified", "https://cs.rochester.edu/u/nhossain/humicroedit.html",
           "The archive's README.txt asks users to cite the task paper and states no licence.",
           "Hossain et al., SemEval-2020 Task 7: Assessing Humor in Edited News Headlines (SemEval 2020)", ("humicroedit", "breadth/arts/humicroedit")),
    Source("cfcolor", "Collaborative Filtering of Color Aesthetics", "none stated for the data", "unspecified", "https://www.dgp.toronto.edu/~donovan/cfcolor/",
           "The archive's only notice (release/runPrediction.m) is the permission notice of Salakhutdinov's PMF code; nothing licenses the rating data itself.",
           "O'Donovan, Agarwala, Hertzmann, Collaborative Filtering of Color Aesthetics (CAe 2014)", ("cfcolor", "breadth/arts/cfcolor")),
)  # fmt: skip
BY_KEY = {s.key: s for s in SOURCES}
_NAMES = {n: s.key for s in SOURCES for n in s.names if not n.endswith("*")}
_PREFIXES = {n[:-1]: s.key for s in SOURCES for n in s.names if n.endswith("*")}
# upstream licence files shipped inside the pinned raw archives: (archive under data/sources, member, file name)
UPSTREAM: dict[str, tuple[tuple[str, str, str], ...]] = {
    "contractnli": (("eval/breadth/language/contractnli/contract-nli.zip", "contract-nli/LICENSE", "LICENSE"),
                    ("eval/breadth/language/contractnli/contract-nli.zip", "contract-nli/TERMS", "TERMS")),
    "sgd": (("eval/breadth/retrieval/sgd/dstc8-schema-guided-dialogue.tar.gz",
             "dstc8-schema-guided-dialogue-e852981ae34990f4358979625854259302feaa78/LICENSE.txt", "LICENSE.txt"),),
    "humicroedit": (("eval/breadth/arts/humicroedit/semeval-2020-task-7-dataset.zip", "semeval-2020-task-7-dataset/README.txt", "README.txt"),),
    "cfcolor": (("eval/breadth/arts/cfcolor/cfcolor.zip", "release/runPrediction.m", "runPrediction.m"),),
}  # fmt: skip


def source_key(name: str) -> str:
    """The registry key of a `_meta.source` value or catalog item name; refuses one the registry doesn't know."""
    if name in _NAMES:
        return _NAMES[name]
    if key := next((k for prefix, k in _PREFIXES.items() if name.startswith(prefix)), None):
        return key
    raise KeyError(f"no licence recorded for source {name!r}: add it to den/licences.py")


def kind(keys: Iterable[str]) -> Kind:
    """The most restrictive class among `keys`."""
    return max((BY_KEY[k].kind for k in keys), key=RANK.__getitem__, default="open")


def allowed(k: Kind, public: bool) -> bool:
    """May a file of class `k` be uploaded: never if restricted, privately if unspecified, else always."""
    return RANK[k] < RANK["restricted" if not public else "unspecified"]


def _raw_items() -> list[tuple[str, str]]:
    """(directory under data/, catalog item name) for every raw item, deepest first."""
    pairs = [(item.dest, item.name) for item in ITEMS if item.dest.startswith("sources/")]
    return sorted(pairs, key=lambda p: -len(p[0]))


def record_keys(record: Mapping[str, object]) -> set[str]:
    """The sources one record holds, from its `_meta`."""
    meta = record.get("_meta")
    keys = set()
    for field in ("source", "parent_source"):
        if isinstance(meta, dict) and (name := meta.get(field)):
            if field == "source" and name == "buried":  # a probe whose text is all its parent dataset's
                continue
            keys.add(source_key(str(name)))
    return keys


def record_kind(record: Mapping[str, object]) -> Kind:
    """One record's licence class; a record that names no source is `unspecified`, never assumed open."""
    keys = record_keys(record)
    return kind(keys) if keys else "unspecified"


def _record_keys(path: Path) -> set[str]:
    keys = set()
    with path.open(encoding="utf-8") as f:
        for line in f:
            if line.strip():
                keys |= record_keys(json.loads(line))
    return keys


def file_keys(root: Path, rel: str) -> set[str]:
    """The sources a file under `root` (data/) holds."""
    parts = rel.split("/")
    if parts[0] == "clean":  # cleaned copies hold what their originals hold
        return (
            file_keys(root, "/".join(parts[1:])) if (root / "/".join(parts[1:])).exists() else _record_keys(root / rel)
        )
    if parts[0] == "sources":
        name = next((n for d, n in _raw_items() if rel.startswith(d + "/")), None)
        if name is None:
            raise KeyError(f"{rel}: under no pinned catalog item")
        return {source_key(name)}
    if _generated(rel):
        return set()
    if parts[0] == "manifests":
        return {"kev"}
    if len(parts) >= 3 and parts[1] == "sources":  # data/<split>/sources/<area>/<name>.jsonl, from normalize
        return {source_key("/".join(parts[2:]).removesuffix(".jsonl"))}
    if rel.endswith(".jsonl"):
        return _record_keys(root / rel)
    raise KeyError(f"{rel}: no rule says whose data this is")


def classify(root: Path, rels: Iterable[str]) -> dict[str, tuple[Kind, list[str]]]:
    """{file: (class, its sources)} for each relative path."""
    out = {}
    for rel in rels:
        keys = sorted(file_keys(root, rel))
        out[rel] = (kind(keys), keys)
    return out


def _source_page(s: Source, files: list[str], excluded: dict[str, str]) -> str:
    texts = "".join(f"\n- [`{t}`](texts/{t}.txt)" for t in s.texts) or "\n- none: the terms are as quoted above"
    upstream = "".join(f"\n- [`upstream/{s.key}/{name}`](upstream/{s.key}/{name})" for _, _, name in UPSTREAM.get(s.key, ()))
    marked = [f"`{f}`" + (" (not in this copy)" if f in excluded else "") for f in files]
    listed = "".join(f"\n- {f}" for f in marked[:40]) + (f"\n- ... and {len(marked) - 40} more" if len(marked) > 40 else "")
    return (
        f"# {s.title}\n\n- Licence: **{s.licence}**\n- Class: **{s.kind}**\n- Terms: <{s.url}>\n- Attribution: {s.attribution}\n\n"
        f"## Evidence\n\n{s.evidence}\n\n## Licence texts\n{texts}{upstream}\n\n## Files that hold it\n{listed or chr(10) + '- none'}\n"
    )


def write(
    root: Path, classified: dict[str, tuple[Kind, list[str]]], excluded: dict[str, str] | None = None, repo: str | None = None
) -> None:
    """The notices, into `root`: `LICENSES/` (one page per source, the canonical texts, upstream licence files),
    `LICENSES.md` (every file's class and sources), `README.md` (the Hub dataset card) and a `SOURCE-LICENSE.md` beside
    every dataset (each raw source's folder, and each folder of suite, normalized or cleaned files). Deterministic: the same files give the same notices."""
    excluded = excluded or {}
    pages = root / "LICENSES"
    shutil.rmtree(pages, ignore_errors=True)
    (pages / "texts").mkdir(parents=True)
    by_source: dict[str, list[str]] = defaultdict(list)
    for rel, (_, keys) in sorted(classified.items()):
        for k in keys:
            by_source[k].append(rel)
    used = sorted(by_source, key=lambda k: BY_KEY[k].title.casefold())
    for spdx in sorted({t for k in used for t in BY_KEY[k].texts}):
        shutil.copyfile(TEXTS / f"{spdx}.txt", pages / "texts" / f"{spdx}.txt")
    for key in used:
        for archive, member, name in UPSTREAM.get(key, ()):
            if (src := root / "sources" / archive).is_file():
                target = pages / "upstream" / key / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(_member(src, member))
        (pages / f"{key}.md").write_text(_source_page(BY_KEY[key], by_source[key], excluded), encoding="utf-8")
    for stale in root.rglob(NOTICE_FILE):  # folders change between runs: every notice is rewritten from scratch
        stale.unlink()
    folders: dict[str, list[str]] = defaultdict(list)
    for rel in classified:
        folders[unit(rel)].append(rel)
    for folder, rels in sorted(folders.items()):
        if folder and _has_data(rels, classified):
            (root / folder / NOTICE_FILE).write_text(folder_notice(root, folder, rels, classified, excluded), encoding="utf-8")
    rows = "\n".join(f"| `{rel}` | {k} | {', '.join(keys) or '(notice)'} |{' excluded: ' + excluded[rel] if rel in excluded else ''}"
                     for rel, (k, keys) in sorted(classified.items()))  # fmt: skip
    (root / "LICENSES.md").write_text(
        "# Licences of every file\n\nEach file takes the most restrictive class among the sources it holds "
        "(`den/licences.py`). Per-source terms, evidence and licence texts: `LICENSES/`.\n\n"
        f"| file | class | sources |\n|---|---|---|\n{rows}\n",
        encoding="utf-8",
    )
    (root / "README.md").write_text(card(used, classified, excluded, repo), encoding="utf-8")


def unit(rel: str) -> str:
    """The folder whose notice covers a file: its pinned raw item's directory (a dataset as downloaded, subfolders
    and all), else the folder it sits in."""
    for dest, _ in _raw_items():
        if rel.startswith(dest + "/"):
            return dest
    return rel.rsplit("/", 1)[0] if "/" in rel else ""


def _has_data(rels: list[str], classified: dict[str, tuple[Kind, list[str]]]) -> bool:
    return any(classified[r][1] for r in rels)


LEGEND = (
    "Each file keeps the licence of every source it holds; a file holding several takes the most restrictive class: "
    "**open** (permissive) < **share-alike** (derived data keeps the licence) < **non-commercial** (non-commercial "
    "use only) < **unspecified** (no licence stated: private copies only) < **restricted** (terms forbid "
    "redistribution: never uploaded)."
)


def folder_notice(
    root: Path, folder: str, rels: list[str], classified: dict[str, tuple[Kind, list[str]]], excluded: dict[str, str]
) -> str:
    """The notice beside a dataset: what each file here holds, and each of those sources' terms."""
    import os

    def link(target: str) -> str:
        return Path(os.path.relpath(root / target, root / folder)).as_posix()

    rows = []
    for rel in sorted(rels):
        k, keys = classified[rel]
        here = f"no ({excluded[rel]}); rebuild from the pinned original" if rel in excluded else "yes"
        titles = ", ".join(f"[{BY_KEY[x].title}]({link(f'LICENSES/{x}.md')})" for x in keys)
        rows.append(f"| `{rel.removeprefix(folder + '/')}` | {k} | {titles} | {here} |")
    sections = []
    for key in sorted({x for r in rels for x in classified[r][1]}, key=lambda x: BY_KEY[x].title.casefold()):
        s = BY_KEY[key]
        texts = ", ".join(f"[{t}]({link(f'LICENSES/texts/{t}.txt')})" for t in s.texts) or "none: the terms are as linked"
        sections.append(
            f"### {s.title}\n\n- Licence: **{s.licence}** ({s.kind})\n- Terms: <{s.url}>\n- Attribution: {s.attribution}\n"
            f"- Licence text: {texts}\n- Evidence and every file holding it: [{link(f'LICENSES/{key}.md')}]({link(f'LICENSES/{key}.md')})\n"
        )
    return (
        f"# Licences: `{folder}/`\n\n{LEGEND}\n\n## Files\n\n| file | class | sources | in this copy |\n|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n\n## Sources\n\n"
        + "\n".join(sections)
    )


def _member(archive: Path, member: str) -> bytes:
    if archive.suffix == ".zip":
        with zipfile.ZipFile(archive) as z:
            return z.read(member)
    with tarfile.open(archive) as t:
        stream = t.extractfile(member)
        assert stream is not None
        return stream.read()


def card(used: list[str], classified: dict[str, tuple[Kind, list[str]]], excluded: dict[str, str], repo: str | None = None) -> str:
    """The Hub dataset card: a mixed-licence dataset, one row per source. The Hub wants `license_link` as an https
    URL, so it points at this repo's LICENSES.md when the card is written for an upload, and is left out otherwise."""
    link = f"\nlicense_link: https://huggingface.co/datasets/{repo}/blob/main/LICENSES.md" if repo else ""
    rows = "\n".join(
        f"| {BY_KEY[k].title} | {BY_KEY[k].licence} | {BY_KEY[k].kind} | [terms]({BY_KEY[k].url}) · [details](LICENSES/{k}.md) |"
        for k in used
    )
    kinds = sorted({k for k, _ in classified.values()}, key=RANK.__getitem__)
    gone = "\n".join(f"- `{rel}`: {why}" for rel, why in sorted(excluded.items())) or "- none"
    noncommercial = "non-commercial" in kinds
    return f"""---
license: other
license_name: mixed-source-licences{link}
pretty_name: den training and evaluation data
tags: [den, system-one, multiple-choice, calibration]
---

# den data

The training, calibration, development and test data of den (github.com/ramput-labs/den): Kev 1.0's frozen suites,
normalized public sources and their cleaned copies. **Each file keeps the licence of the sources it holds**; there is
no single licence for the whole. `LICENSES.md` lists every file's sources and class, `LICENSES/` holds each source's
terms, the evidence they were read from, the canonical licence texts and the licence files shipped with the data.
{"Some sources are **non-commercial** (CC-BY-NC or research-only): files holding them may be used for non-commercial research only." if noncommercial else ""}
Share-alike sources (CC-BY-SA) require derived data to keep their licence. Cite the sources below when you use them.

## Sources

| source | licence | class | terms |
|---|---|---|---|
{rows}

## Not in this copy

Files whose sources may not be redistributed (or have no stated licence, in a public copy) were left out;
`make data-download` downloads this copy and rebuilds them from the pinned originals:

{gone}

Classes are conservative readings of each source's own terms, recorded with their evidence; they are not legal advice.
"""


def data_files(root: Path) -> list[str]:
    """Every file under `root` that belongs in a copy of it: not caches, staging or partial downloads."""
    found = (p for p in sorted(root.rglob("*")) if p.is_file())
    return [rel for p in found if not any(fnmatch(rel := p.relative_to(root).as_posix(), pat) for pat in IGNORE)]


def notices(
    root: Path, public: bool = False, repo: str | None = None
) -> tuple[dict[str, tuple[Kind, list[str]]], dict[str, str]]:
    """Classify every data file, write the notices, and return the classes and the files a copy must leave out."""
    rels = [r for r in data_files(root) if not _generated(r)]
    classified = classify(root, rels)
    excluded = {rel: f"{k}: {', '.join(BY_KEY[x].title for x in keys if BY_KEY[x].kind == k)}"
                for rel, (k, keys) in classified.items() if not allowed(k, public)}  # fmt: skip
    write(root, classified, excluded, repo)
    return classified, excluded


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="den licences")
    p.add_argument("--root", type=Path, default=Path("data"))
    p.add_argument("--public", action="store_true", help="list what a public copy would leave out")
    args = p.parse_args(argv)
    classified, excluded = notices(args.root, args.public)
    counts: dict[str, int] = defaultdict(int)
    for k, _ in classified.values():
        counts[k] += 1
    print("  ".join(f"{k} {counts[k]}" for k in RANK if counts[k]) + f"  ({len(classified)} files)")
    for rel, why in sorted(excluded.items()):
        print(f"  left out of a {'public' if args.public else 'private'} copy: {rel}  ({why})")
    print(
        f"wrote {args.root}/LICENSES.md, {args.root}/LICENSES/, {args.root}/README.md and a {NOTICE_FILE} beside every dataset"
    )
    return 0
